DROP TABLE SYSTEM.POS_CESTADO_CIVL CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_CESTADO_CIVL
(
  CEC_PK_ESTADO_CIVIL  NUMBER(2)                NOT NULL,
  CEC_ESATADO_CIVIL    VARCHAR2(100 BYTE)       NOT NULL,
  CEC_FK_ESTATUS       NUMBER(2)                DEFAULT 2                     NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.POS_CESTADO_CIVL_PK ON SYSTEM.POS_CESTADO_CIVL
(CEC_PK_ESTADO_CIVIL)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SYSTEM.POS_CESTADO_CIVL ADD (
  CONSTRAINT POS_CESTADO_CIVL_PK
  PRIMARY KEY
  (CEC_PK_ESTADO_CIVIL)
  USING INDEX SYSTEM.POS_CESTADO_CIVL_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_CESTADO_CIVL ADD (
  CONSTRAINT POS_CESTADO_CIVL_R01 
  FOREIGN KEY (CEC_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);
