DROP TABLE SYSTEM.POS_TUSUARIO_ROL CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_TUSUARIO_ROL
(
  PTR_PK_USUARIO_ROL  NUMBER(10)                NOT NULL,
  PTR_FK_USUARIO      NUMBER(10)                NOT NULL,
  PTR_FK_ROL          NUMBER(10)                NOT NULL,
  PTR_FK_ESTATUS      NUMBER(2)                 DEFAULT 2
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.POS_TUSUARIO_ROL_PK ON SYSTEM.POS_TUSUARIO_ROL
(PTR_PK_USUARIO_ROL)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SYSTEM.POS_TUSUARIO_ROL ADD (
  CONSTRAINT POS_TUSUARIO_ROL_PK
  PRIMARY KEY
  (PTR_PK_USUARIO_ROL)
  USING INDEX SYSTEM.POS_TUSUARIO_ROL_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_TUSUARIO_ROL ADD (
  CONSTRAINT POS_TUSUARIO_ROL_R01 
  FOREIGN KEY (PTR_FK_USUARIO) 
  REFERENCES SYSTEM.POS_TUSUARIO (PTU_PK_USUARIO)
  ENABLE VALIDATE
,  CONSTRAINT POS_TUSUARIO_ROL_R02 
  FOREIGN KEY (PTR_FK_ROL) 
  REFERENCES SYSTEM.POS_CROLES (PTR_PK_ROL)
  ENABLE VALIDATE
,  CONSTRAINT POS_TUSUARIO_ROL_R03 
  FOREIGN KEY (PTR_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);
