DROP TABLE SYSTEM.POS_TUSUARIO CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_TUSUARIO
(
  PTU_PK_USUARIO      NUMBER(10)                NOT NULL,
  PTU_USUARIO         VARCHAR2(200 BYTE)        NOT NULL,
  PTU_CONTRASENA      VARCHAR2(200 BYTE)        NOT NULL,
  PTU_FK_ALUMNO       NUMBER(10),
  PTU_NOMBRE          VARCHAR2(200 BYTE)        NOT NULL,
  PTU_AP_PATERNO      VARCHAR2(200 BYTE),
  PTU_AP_MATERNO      VARCHAR2(200 BYTE),
  PTU_FK_UR           VARCHAR2(10 BYTE)         DEFAULT 'O2P000',
  PTU_FK_ESTATUS      NUMBER(2)                 DEFAULT 1                     NOT NULL,
  PTU_FECHA_CREACION  DATE                      DEFAULT SYSDATE               NOT NULL,
  PTU_RFC             VARCHAR2(13 BYTE)         NOT NULL,
  PTU_CURP            VARCHAR2(18 BYTE)         NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.POS_TUSUARIO_PK ON SYSTEM.POS_TUSUARIO
(PTU_PK_USUARIO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SYSTEM.POS_TUSUARIO ADD (
  CONSTRAINT POS_TUSUARIO_PK
  PRIMARY KEY
  (PTU_PK_USUARIO)
  USING INDEX SYSTEM.POS_TUSUARIO_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_TUSUARIO ADD (
  CONSTRAINT POS_TUSUARIO_R01 
  FOREIGN KEY (PTU_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);
