DROP TABLE SYSTEM.POS_CROLES CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_CROLES
(
  PTR_PK_ROL      NUMBER(10)                    NOT NULL,
  PTR_ROL         VARCHAR2(200 BYTE)            NOT NULL,
  PTR_FK_ESTATUS  NUMBER(2)                     DEFAULT 2                     NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.POS_TROLES_PK ON SYSTEM.POS_CROLES
(PTR_PK_ROL)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SYSTEM.POS_CROLES ADD (
  CONSTRAINT POS_CROLES_PK
  PRIMARY KEY
  (PTR_PK_ROL)
  USING INDEX SYSTEM.POS_TROLES_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_CROLES ADD (
  CONSTRAINT POS_CROLES_R01 
  FOREIGN KEY (PTR_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);
