DROP PACKAGE SYSTEM.P_POS_ALUMNO;

CREATE OR REPLACE PACKAGE SYSTEM.P_POS_ALUMNO AS
/******************************************************************************
   NAME:       P_POS_ALUMNO
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        19/02/2020      jegomezt       1. Created this package.
******************************************************************************/

  
  PROCEDURE CREA_CUENTA(ARG_NOMBRE IN  SYSTEM.POS_TUSUARIO.PTU_NOMBRE%TYPE,
  ARG_APELLIDOPAT IN SYSTEM.POS_TUSUARIO.PTU_AP_PATERNO%TYPE,
  ARG_APELLIDOMAT IN SYSTEM.POS_TUSUARIO.PTU_AP_MATERNO%TYPE,
  ARG_RFC IN SYSTEM.POS_TUSUARIO.PTU_RFC%TYPE,
  ARG_CURP IN SYSTEM.POS_TUSUARIO.PTU_CURP%TYPE,
  ARG_USUARIO IN SYSTEM.POS_TUSUARIO.PTU_USUARIO%TYPE,
  ARG_PASS IN SYSTEM.POS_TUSUARIO.PTU_CONTRASENA%TYPE,
  resultado OUT NUMBER);
  

END P_POS_ALUMNO;
/

DROP PACKAGE BODY SYSTEM.P_POS_ALUMNO;

CREATE OR REPLACE PACKAGE BODY SYSTEM.P_POS_ALUMNO IS
 PROCEDURE CREA_CUENTA(ARG_NOMBRE IN  SYSTEM.POS_TUSUARIO.PTU_NOMBRE%TYPE,
  ARG_APELLIDOPAT IN SYSTEM.POS_TUSUARIO.PTU_AP_PATERNO%TYPE,
  ARG_APELLIDOMAT IN SYSTEM.POS_TUSUARIO.PTU_AP_MATERNO%TYPE,
  ARG_RFC IN SYSTEM.POS_TUSUARIO.PTU_RFC%TYPE,
  ARG_CURP IN SYSTEM.POS_TUSUARIO.PTU_CURP%TYPE,
  ARG_USUARIO IN SYSTEM.POS_TUSUARIO.PTU_USUARIO%TYPE,
  ARG_PASS IN SYSTEM.POS_TUSUARIO.PTU_CONTRASENA%TYPE,
  resultado OUT NUMBER) IS
 BEGIN
   INSERT INTO SYSTEM.POS_TUSUARIO(PTU_PK_USUARIO, PTU_USUARIO, PTU_CONTRASENA, PTU_NOMBRE, PTU_AP_PATERNO,PTU_AP_MATERNO,PTU_RFC,PTU_CURP)
   VALUES(POS_SEC_USUARIO.NEXTVAL,ARG_USUARIO,ARG_PASS,ARG_NOMBRE,ARG_APELLIDOPAT,ARG_APELLIDOMAT,ARG_RFC,ARG_CURP)
   RETURNING PTU_PK_USUARIO INTO resultado;
   IF resultado >0 THEN --SI INSERTA EL REGISTRO EN USUARIOS, LE AGREGA EL ROL DE ASPIRANTE
        INSERT INTO SYSTEM.POS_TUSUARIO_ROL(PTR_PK_USUARIO_ROL,PTR_FK_USUARIO,PTR_FK_ROL)
        VALUES(POS_SEC_TUSUARIO_ROL.NEXTVAL,resultado,1);
   END IF;
   COMMIT;
 END CREA_CUENTA; 
END;
/
