DROP TABLE SYSTEM.POS_CESTATUS CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_CESTATUS
(
  PCE_PK_ESTATUS  NUMBER(2)                     NOT NULL,
  PCE_ESTATUS     VARCHAR2(50 BYTE)             NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SYSTEM.POS_CNIVEL_ACADEMICO CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_CNIVEL_ACADEMICO
(
  CNA_PK_NIVEL_ACADEMICO  NUMBER(10)            NOT NULL,
  CNA_NIVEL_ACADEMICO     VARCHAR2(200 BYTE)    NOT NULL,
  CNA_FK_ESTATUS          NUMBER(2)             DEFAULT 2                     NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SYSTEM.POS_CROLES CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_CROLES
(
  PTR_PK_ROL      NUMBER(10)                    NOT NULL,
  PTR_ROL         VARCHAR2(200 BYTE)            NOT NULL,
  PTR_FK_ESTATUS  NUMBER(2)                     DEFAULT 2                     NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SYSTEM.POS_TUSUARIO CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_TUSUARIO
(
  PTU_PK_USUARIO      NUMBER(10)                NOT NULL,
  PTU_USUARIO         VARCHAR2(200 BYTE)        NOT NULL,
  PTU_CONTRASENA      VARCHAR2(200 BYTE)        NOT NULL,
  PTU_FK_ALUMNO       NUMBER(10),
  PTU_NOMBRE          VARCHAR2(200 BYTE)        NOT NULL,
  PTU_AP_PATERNO      VARCHAR2(200 BYTE),
  PTU_AP_MATERNO      VARCHAR2(200 BYTE),
  PTU_FK_UR           VARCHAR2(10 BYTE)         DEFAULT 'O2P000',
  PTU_FK_ESTATUS      NUMBER(2)                 DEFAULT 1                     NOT NULL,
  PTU_FECHA_CREACION  DATE                      DEFAULT SYSDATE               NOT NULL,
  PTU_RFC             VARCHAR2(13 BYTE)         NOT NULL,
  PTU_CURP            VARCHAR2(18 BYTE)         NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SYSTEM.POS_TUSUARIO_ROL CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_TUSUARIO_ROL
(
  PTR_PK_USUARIO_ROL  NUMBER(10)                NOT NULL,
  PTR_FK_USUARIO      NUMBER(10)                NOT NULL,
  PTR_FK_ROL          NUMBER(10)                NOT NULL,
  PTR_FK_ESTATUS      NUMBER(2)                 DEFAULT 2
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.POS_CESTATUS_PK ON SYSTEM.POS_CESTATUS
(PCE_PK_ESTATUS)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX SYSTEM.POS_CNIVEL_ACADEMICO_PK ON SYSTEM.POS_CNIVEL_ACADEMICO
(CNA_PK_NIVEL_ACADEMICO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX SYSTEM.POS_TROLES_PK ON SYSTEM.POS_CROLES
(PTR_PK_ROL)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX SYSTEM.POS_TUSUARIO_PK ON SYSTEM.POS_TUSUARIO
(PTU_PK_USUARIO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX SYSTEM.POS_TUSUARIO_ROL_PK ON SYSTEM.POS_TUSUARIO_ROL
(PTR_PK_USUARIO_ROL)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

DROP TABLE SYSTEM.POS_CESTADO_CIVL CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.POS_CESTADO_CIVL
(
  CEC_PK_ESTADO_CIVIL  NUMBER(2)                NOT NULL,
  CEC_ESATADO_CIVIL    VARCHAR2(100 BYTE)       NOT NULL,
  CEC_FK_ESTATUS       NUMBER(2)                DEFAULT 2                     NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.POS_CESTADO_CIVL_PK ON SYSTEM.POS_CESTADO_CIVL
(CEC_PK_ESTADO_CIVIL)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SYSTEM.POS_CESTATUS ADD (
  CONSTRAINT POS_CESTATUS_PK
  PRIMARY KEY
  (PCE_PK_ESTATUS)
  USING INDEX SYSTEM.POS_CESTATUS_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_CNIVEL_ACADEMICO ADD (
  CONSTRAINT POS_CNIVEL_ACADEMICO_PK
  PRIMARY KEY
  (CNA_PK_NIVEL_ACADEMICO)
  USING INDEX SYSTEM.POS_CNIVEL_ACADEMICO_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_CROLES ADD (
  CONSTRAINT POS_CROLES_PK
  PRIMARY KEY
  (PTR_PK_ROL)
  USING INDEX SYSTEM.POS_TROLES_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_TUSUARIO ADD (
  CONSTRAINT POS_TUSUARIO_PK
  PRIMARY KEY
  (PTU_PK_USUARIO)
  USING INDEX SYSTEM.POS_TUSUARIO_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_TUSUARIO_ROL ADD (
  CONSTRAINT POS_TUSUARIO_ROL_PK
  PRIMARY KEY
  (PTR_PK_USUARIO_ROL)
  USING INDEX SYSTEM.POS_TUSUARIO_ROL_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_CESTADO_CIVL ADD (
  CONSTRAINT POS_CESTADO_CIVL_PK
  PRIMARY KEY
  (CEC_PK_ESTADO_CIVIL)
  USING INDEX SYSTEM.POS_CESTADO_CIVL_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_CNIVEL_ACADEMICO ADD (
  CONSTRAINT POS_CNIVEL_ACADEMICO_R01 
  FOREIGN KEY (CNA_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_CROLES ADD (
  CONSTRAINT POS_CROLES_R01 
  FOREIGN KEY (PTR_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_TUSUARIO ADD (
  CONSTRAINT POS_TUSUARIO_R01 
  FOREIGN KEY (PTU_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_TUSUARIO_ROL ADD (
  CONSTRAINT POS_TUSUARIO_ROL_R01 
  FOREIGN KEY (PTR_FK_USUARIO) 
  REFERENCES SYSTEM.POS_TUSUARIO (PTU_PK_USUARIO)
  ENABLE VALIDATE
,  CONSTRAINT POS_TUSUARIO_ROL_R02 
  FOREIGN KEY (PTR_FK_ROL) 
  REFERENCES SYSTEM.POS_CROLES (PTR_PK_ROL)
  ENABLE VALIDATE
,  CONSTRAINT POS_TUSUARIO_ROL_R03 
  FOREIGN KEY (PTR_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);

ALTER TABLE SYSTEM.POS_CESTADO_CIVL ADD (
  CONSTRAINT POS_CESTADO_CIVL_R01 
  FOREIGN KEY (CEC_FK_ESTATUS) 
  REFERENCES SYSTEM.POS_CESTATUS (PCE_PK_ESTATUS)
  ENABLE VALIDATE);
